default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: singh
  password: singh@2024
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: my_notes_backend_development
test:
  <<: *default
  database: my_notes_backend_development
production:
  primary: &primary_production
    <<: *default
    database: my_notes_backend_production
    username: my_notes_backend
    password: <%= ENV["MY_NOTES_BACKEND_DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: my_notes_backend_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: my_notes_backend_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: my_notes_backend_production_cable
    migrations_paths: db/cable_migrate
